# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_world.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hello_world.proto\x12\nhelloworld\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x0bNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tNameReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x86\x01\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12;\n\x07SayName\x12\x17.helloworld.NameRequest\x1a\x15.helloworld.NameReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_world_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=33
  _HELLOREQUEST._serialized_end=61
  _HELLOREPLY._serialized_start=63
  _HELLOREPLY._serialized_end=92
  _NAMEREQUEST._serialized_start=94
  _NAMEREQUEST._serialized_end=121
  _NAMEREPLY._serialized_start=123
  _NAMEREPLY._serialized_end=151
  _GREETER._serialized_start=154
  _GREETER._serialized_end=288
# @@protoc_insertion_point(module_scope)
